### ISSUE TITLE
[node] Negative balance when attempting to install a dapp

### ISSUE THREAD

**Issue by joelalejandro** [counterfactual/monorepo#2198] opened 2019-08-16 20:27 UTC
**Proposal payload**
```json
{
   "methodName":"chan_proposeInstallVirtual",
   "parameters":{
      "timeout":{
         "_hex":"0x02a300"
      },
      "responderDeposit":{
         "_hex":"0x2386f26fc10000"
      },
      "initiatorDeposit":{
         "_hex":"0x2386f26fc10000"
      },
      "proposedToIdentifier":"xpub6De7Jxe92VU7BRAKc2QXKYrtCCXMwjh7TNvEJsJGPgdCJcUDRetDYnyJpe21Q3hNuWe3m7gkLpDrgPgvBiAjeptHQcKxsGyXhPWwF2Ha9YN",
      "initialState":{
         "versionNumber":0,
         "winner":0,
         "board":[
            [
               0,
               0,
               0
            ],
            [
               0,
               0,
               0
            ],
            [
               0,
               0,
               0
            ]
         ]
      },
      "intermediaries":[
         "xpub6DyB9nwZU71An5NQSeuDWKw6M3T8J5BHVbzVALkvtmbbPvZ64g4hXD8n3AtPZHVAuLWCDoW61iAVskqTLz6Y48P4GMmwnZCNzkjyxMzMWR8"
      ],
      "appDefinition":"0x3d2623d5fcAf027BD3c9286E4Fb0CdEF52807532",
      "abiEncodings":{
         "actionEncoding":"tuple(uint8 actionType, uint256 playX, uint256 playY, tuple(uint8 winClaimType, uint256 idx) winClaim)",
         "stateEncoding":"tuple(uint256 versionNumber, uint256 winner, uint256[3][3] board)"
      },
      "outcomeType":"TWO_PARTY_FIXED_OUTCOME"
   },
   "id":1565813346421
}
```

**Related source code**
https://github.com/counterfactual/monorepo/blob/master/packages/node/src/models/free-balance.ts#L162-L186

**Stack trace for error**
```
Stack Trace: Error: FreeBalanceClass::increment ended up with a negative balance when
            merging {} and {"0x8bbf8C3684A57DEd7c8eE5C15A87458cb1C56EDb":{"_hex":"-0x2386f26fc10000"},"0x36e81BfB91adc940d9834337c354B16BCD9876A4":{"_hex":"-0x2386f26fc10000"}}
```

**Steps to reproduce**
- On the `monorepo`:
  1. Sync with `master`.
  2. Run `yarn test:e2e:setup` to build Metamask with the latest Node.
  3. Add the unpacked extension from `packages/greenboard/extension` to your browser.
  4. Setup a MetaMask account.
  5. Run `yarn run:wallet` on the monorepo root.
- On the `dapps-bots` repo:
  1. Run `git pull && git checkout alon-joel/high-roller-metamask`.
  2. Update the `@counterfactual/*` dependencies to the latest versions.
  3. Run `yarn` to fetch the dependencies.
  4. Run `yarn start`.
- On the browser:
  1. Setup a Counterfactual account with the wallet.
  2. Open the High Roller dApp (`http://localhost:3334`). 
  3. Place a bet and you should be matched against the bot.
  4. Look at the bot's Node logs.

**Comment by cf19drofxots** [comment] 2019-09-02 09:24
Sorry for the late reply on this - are there steps I could use to repro?

**Comment by snario** [comment] 2019-09-02 13:42
The error: `merging {} and {"0x8bbf8C3684A57DEd7c8eE5C15A87458cb1C56EDb":{"_hex":"-0x2386f26fc10000"},"0x36e81BfB91adc940d9834337c354B16BCD9876A4":{"_hex":"-0x2386f26fc10000"}}` makes me think that the FreeBalance app has no funds inside of it which is strange.

**Comment by cf19drofxots** [comment] 2019-09-04 10:59
Currently running into
```
$ yarn start
yarn run v1.17.3
$ env-cmd -e development ts-node src/
/Users/nima/Counterfactual/dapps-bots/packages/tic-tac-toe-bot/src/index.ts:1
(function (exports, require, module, __filename, __dirname) { import { confirmFirebaseConfigurationEnvVars, confirmLocalFirebaseConfigurationEnvVars, devAndTestingEnvironments, FIREBASE_CONFIGURATION_ENV_KEYS, FirebaseServiceFactory } from "@counterfactual/firebase-client";
                                                                     ^

SyntaxError: Unexpected token {
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10)
    at Object.runInThisContext (vm.js:326:10)
    at Module._compile (internal/modules/cjs/loader.js:664:28)
    at Module.m._compile (/Users/nima/Counterfactual/dapps-bots/node_modules/ts-node/src/index.ts:473:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/nima/Counterfactual/dapps-bots/node_modules/ts-node/src/index.ts:476:12)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Command failed: /usr/local/Cellar/yvm/3.4.0/versions/v1.17.3/bin/yarn.js start
```

when trying to run the bots

**Comment by cf19drofxots** [comment] 2019-09-05 10:01
Status update: got the bot to create a channel with the hub but investigating why a channel can't be created from the wallet.

**Comment by cf19drofxots** [comment] 2019-09-05 10:49
@joelalejandro can you confirm if when the bots get started, that they've actually deposited funds into their channel with the hub?

Reasons why I ask:
1. I don't see that in the repro instructions
2. Negative balance errors occurs when the channel balance is insufficient (which it obviously would be if the bot and hub haven't deposited into their channel)
3. I'm running into issues when having the bot deposit into the channel (so if you've also deposited, I'm curious why I'd be running into this error)

**Comment by cf19drofxots** [comment] 2019-09-05 15:30
Consistently running into this while trying to deposit with the bot

```
@counterfactual/simple-hub-server: (node:49457) UnhandledPromiseRejectionWarning: Error: k undefined
@counterfactual/simple-hub-server:     at sanitizeXkeyAndK (/Users/nima/Counterfactual/monorepo/packages/node/src/machine/xkeys.ts:34:11)
@counterfactual/simple-hub-server:     at xkeyKthAddress (/Users/nima/Counterfactual/monorepo/packages/node/src/machine/xkeys.ts:40:3)
@counterfactual/simple-hub-server:     at sortAddresses$1.userNeuteredExtendedKeys.map.xpub (/Users/nima/Counterfactual/monorepo/packages/node/src/models/state-channel.ts:162:9)
@counterfactual/simple-hub-server:     at Array.map (<anonymous>)
@counterfactual/simple-hub-server:     at StateChannel.getSigningKeysFor (/Users/nima/Counterfactual/monorepo/packages/node/src/models/state-channel.ts:161:37)
@counterfactual/simple-hub-server:     at StateChannel.installApp (/Users/nima/Counterfactual/monorepo/packages/node/src/models/state-channel.ts:419:31)
@counterfactual/simple-hub-server:     at computeStateChannelTransition (/Users/nima/Counterfactual/monorepo/packages/node/src/protocol/install.ts:363:23)
@counterfactual/simple-hub-server:     at /Users/nima/Counterfactual/monorepo/packages/node/src/protocol/install.ts:186:38
@counterfactual/simple-hub-server:     at Generator.next (<anonymous>)
@counterfactual/simple-hub-server:     at resume (/Users/nima/Counterfactual/monorepo/packages/node/dist/index.js:52:44)
@counterfactual/simple-hub-server:     at /Users/nima/Counterfactual/monorepo/packages/node/dist/index.js:51:121
@counterfactual/simple-hub-server:     at new Promise (<anonymous>)
@counterfactual/simple-hub-server:     at Object.i.(anonymous function) [as next] (/Users/nima/Counterfactual/monorepo/packages/node/dist/index.js:51:63)
@counterfactual/simple-hub-server:     at InstructionExecutor.runProtocol (/Users/nima/Counterfactual/monorepo/packages/node/src/machine/instruction-executor.ts:148:33)
@counterfactual/simple-hub-server:     at InstructionExecutor.runProtocolWithMessage (/Users/nima/Counterfactual/monorepo/packages/node/src/machine/instruction-executor.ts:99:17)
@counterfactual/simple-hub-server:     at executeFunctionWithinQueues (/Users/nima/Counterfactual/monorepo/packages/node/src/message-handling/handle-protocol-message.ts:56:58)
@counterfactual/simple-hub-server: (node:49457) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
```

**Comment by cf19drofxots** [comment] 2019-09-05 17:02
@Alonski @joelalejandro the latest commit on the branch[0] is brought up to date with the latest node code to ensure proper channel setup and funding across both sides.

@Alonski try giving that a shot as the error for negative balances has only ever occurred when channels don't have sufficient balances (when they're not funded).

[0]: https://github.com/counterfactual/dapps-bots/tree/alon-joel/high-roller-metamask 

I'm closing this issue because the issue of negative balances is a matter of proper channel funding. If you manage to repro _this_ issue even after having confirmed both the user<->hub and hub<->bot channels have been properly funded, we can re-open this.

**Closed by cf19drofxots** 2019-09-05 17:02 UTC
Labels: 🐞 Bug, 📦 Node
