### ISSUE TITLE
Empty bytecode is caught too late

### ISSUE THREAD

**Issue by IIIIllllIIIIllllIIIIllllIIIIllllIIIIll** [counterfactual/monorepo#1326] opened 2019-04-18 09:05 UTC
solc occasionally produces empty bytecode. This should be caught at build time instead of after deploying and trying to use the contract.

**Comment by AlexXiong97** [comment] 2019-04-26 04:37
is this probabilistic or reproducible?

**Comment by IIIIllllIIIIllllIIIIllllIIIIllllIIIIll** [comment] 2019-04-26 05:12
Reproducible in the sense that artifacts with empty bytecode are always deployed successfully AFAICT. I think waffle should be patched to warn/error of empty bytecode.

**Comment by snario** [comment] 2019-05-08 18:03
@IIIIllllIIIIllllIIIIllllIIIIllllIIIIll I believe we identified the root cause of this issue and it is not probabilistic. I'm going to close this.

For the reader: Inheriting an abstract contract and leaving a method unimplemented keep the inherited contract as abstract which has empty bytecode.

**Closed by snario** 2019-05-08 18:03 UTC
